import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { incomeStatement, balanceSheet } from "./accounting";
import { formatGHS } from "./format";

function htmlReport(profile, range, is, bs) {
  const business = profile?.business_name || "Your Business";
  const periodLabel = range.label;
  const today = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  const rowStyle = `style="padding:6px 0;border-bottom:1px solid #e5e7eb;"`;
  const totalStyle = `style="padding:8px 0;border-top:2px solid #0F1F3D;font-weight:bold;"`;
  const sectionTitle = `style="color:#0F1F3D;font-size:13px;font-weight:bold;text-transform:uppercase;letter-spacing:0.5px;margin:18px 0 8px;"`;
  const grandStyle = `style="background:#0F1F3D;color:#fff;padding:10px 12px;border-radius:8px;margin-top:8px;display:flex;justify-content:space-between;"`;

  function lineRows(lines) {
    if (!lines || lines.length === 0) {
      return `<tr><td colspan="2" ${rowStyle}>No activity</td></tr>`;
    }
    return lines
      .map(
        (r) =>
          `<tr>
            <td ${rowStyle}>${r.name || r.label}</td>
            <td ${rowStyle} style="text-align:right;">${formatGHS(r.amount !== undefined ? r.amount : r.balance)}</td>
          </tr>`,
      )
      .join("");
  }

  const isRevenue = lineRows(is.revenueLines);
  const isExpense = lineRows(is.expenseLines);
  const bsAssets = lineRows(bs.assets);
  const bsLiabilities = lineRows(bs.liabilities);
  const bsEquity = lineRows([
    ...bs.equity.map((a) => ({ name: a.name, balance: a.balance })),
    { name: "Retained earnings", balance: bs.retainedEarnings },
  ]);

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Financial Report — ${business}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 24px; color: #111; background: #fff; }
  h1 { font-size: 20px; margin: 0 0 4px; color: #0F1F3D; }
  .meta { font-size: 12px; color: #666; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  .page-break { page-break-before: always; }
  .footer { margin-top: 40px; font-size: 11px; color: #888; border-top: 1px solid #eee; padding-top: 10px; }
</style>
</head>
<body>
  <h1>${business}</h1>
  <div class="meta">Period: ${periodLabel} &nbsp;|&nbsp; Generated: ${today}</div>

  <div ${sectionTitle}>Income Statement</div>
  <table>
    <tbody>
      ${isRevenue}
      <tr><td ${totalStyle}>Total revenue</td><td ${totalStyle} style="text-align:right;">${formatGHS(is.totalRevenue)}</td></tr>
    </tbody>
  </table>

  <table style="margin-top:12px;">
    <tbody>
      ${isExpense}
      <tr><td ${totalStyle}>Total expenses</td><td ${totalStyle} style="text-align:right;">${formatGHS(is.totalExpenses)}</td></tr>
    </tbody>
  </table>

  <div ${grandStyle}>
    <span>${is.netIncome >= 0 ? "Net profit" : "Net loss"}</span>
    <span>${formatGHS(Math.abs(is.netIncome))}</span>
  </div>

  <div class="page-break"></div>

  <div ${sectionTitle}>Statement of Financial Position</div>
  <table>
    <tbody>
      ${bsAssets}
      <tr><td ${totalStyle}>Total assets</td><td ${totalStyle} style="text-align:right;">${formatGHS(bs.totalAssets)}</td></tr>
    </tbody>
  </table>

  <table style="margin-top:12px;">
    <tbody>
      ${bsLiabilities}
      <tr><td ${totalStyle}>Total liabilities</td><td ${totalStyle} style="text-align:right;">${formatGHS(bs.totalLiabilities)}</td></tr>
    </tbody>
  </table>

  <table style="margin-top:12px;">
    <tbody>
      ${bsEquity}
      <tr><td ${totalStyle}>Total equity</td><td ${totalStyle} style="text-align:right;">${formatGHS(bs.totalEquity)}</td></tr>
    </tbody>
  </table>

  <div ${grandStyle}>
    <span>Liabilities + Equity</span>
    <span>${formatGHS(bs.totalLiabilities + bs.totalEquity)}</span>
  </div>

  <div class="footer">
    Generated by ${business} Accounting System &middot; ${today}
  </div>
</body>
</html>`;
}

export async function shareFinancialReport(range, profile) {
  const is = incomeStatement(range.start, range.end);
  const bs = balanceSheet(range.end);
  const html = htmlReport(profile, range, is, bs);

  const { uri } = await Print.printToFileAsync({ html });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "Save financial report",
    });
  } else {
    throw new Error("Sharing is not available on this device.");
  }
}
