/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesNewRouteImport } from './routes/sales.new'
import { Route as PurchasesNewRouteImport } from './routes/purchases.new'
import { Route as ExpensesNewRouteImport } from './routes/expenses.new'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesRoute,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasesRoute,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ExpensesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRouteWithChildren
  '/purchases': typeof PurchasesRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/setup': typeof SetupRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/new': typeof SalesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRouteWithChildren
  '/purchases': typeof PurchasesRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/setup': typeof SetupRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/new': typeof SalesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRouteWithChildren
  '/purchases': typeof PurchasesRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/setup': typeof SetupRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/new': typeof SalesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/expenses'
    | '/purchases'
    | '/sales'
    | '/setup'
    | '/expenses/new'
    | '/purchases/new'
    | '/sales/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/expenses'
    | '/purchases'
    | '/sales'
    | '/setup'
    | '/expenses/new'
    | '/purchases/new'
    | '/sales/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/expenses'
    | '/purchases'
    | '/sales'
    | '/setup'
    | '/expenses/new'
    | '/purchases/new'
    | '/sales/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRouteWithChildren
  PurchasesRoute: typeof PurchasesRouteWithChildren
  SalesRoute: typeof SalesRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof SalesRoute
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof PurchasesRoute
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof ExpensesRoute
    }
  }
}

interface ExpensesRouteChildren {
  ExpensesNewRoute: typeof ExpensesNewRoute
}

const ExpensesRouteChildren: ExpensesRouteChildren = {
  ExpensesNewRoute: ExpensesNewRoute,
}

const ExpensesRouteWithChildren = ExpensesRoute._addFileChildren(
  ExpensesRouteChildren,
)

interface PurchasesRouteChildren {
  PurchasesNewRoute: typeof PurchasesNewRoute
}

const PurchasesRouteChildren: PurchasesRouteChildren = {
  PurchasesNewRoute: PurchasesNewRoute,
}

const PurchasesRouteWithChildren = PurchasesRoute._addFileChildren(
  PurchasesRouteChildren,
)

interface SalesRouteChildren {
  SalesNewRoute: typeof SalesNewRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesNewRoute: SalesNewRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRouteWithChildren,
  PurchasesRoute: PurchasesRouteWithChildren,
  SalesRoute: SalesRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
